"""participants and splits

Revision ID: 8a40c68b37ec
Revises: 6325ba7ac8e6
Create Date: 2026-04-18 08:06:59.871605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a40c68b37ec'
down_revision: Union[str, None] = '6325ba7ac8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'display_name', name='uq_event_display_name')
    )
    op.create_table('expense_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['event_participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_id', 'participant_id', name='uq_expense_participant')
    )
    op.alter_column('events', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('expenses', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('expenses', 'payer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('expenses_payer_id_fkey', 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'event_participants', ['payer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key('expenses_payer_id_fkey', 'expenses', 'users', ['payer_id'], ['id'])
    op.alter_column('expenses', 'payer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('expenses', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('expense_splits')
    op.drop_table('event_participants')
    # ### end Alembic commands ###
